-- Bootstrap minimal Bloc 6D Phase 2 (Supabase Postgres isolé).
\set ON_ERROR_STOP on

create extension if not exists pgcrypto;
create schema if not exists auth;

create table if not exists auth.users (
  id uuid primary key
);

do $$
begin
  execute $fn$
    create or replace function auth.jwt()
    returns jsonb language sql stable as $body$
      select coalesce(
        nullif(current_setting('request.jwt.claims', true), '')::jsonb,
        '{}'::jsonb
      );
    $body$
  $fn$;
exception when insufficient_privilege then null;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
end;
$$;

grant usage on schema public to authenticated, anon;
grant usage on schema auth to authenticated, anon;

create or replace function public.current_app_role()
returns text language sql stable as $$
  select nullif(auth.jwt() -> 'app_metadata' ->> 'role', '')
$$;

create or replace function public.is_admin_user()
returns boolean language sql stable as $$
  select public.current_app_role() = 'admin'
$$;

create or replace function public.is_direction_user()
returns boolean language sql stable as $$
  select public.current_app_role() = 'direction'
$$;

create or replace function public.current_app_permissions()
returns text[] language sql stable as $$
  select coalesce(
    (
      select array_agg(x)
      from jsonb_array_elements_text(
        coalesce(auth.jwt() -> 'app_metadata' -> 'permissions', '[]'::jsonb)
      ) as x
    ),
    '{}'::text[]
  )
$$;

create or replace function public.has_app_permission(p_permission text)
returns boolean language sql stable as $$
  select public.is_direction_user()
    and p_permission = any (public.current_app_permissions())
$$;

create or replace function public.set_commissions_row_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

create or replace function public.normalize_organization_id(p_value text)
returns text language sql immutable as $$
  select case
    when p_value is null then null
    when lower(btrim(p_value)) ~ '^[a-z0-9_]+$' then lower(btrim(p_value))
    else null
  end;
$$;

create or replace function public.current_user_organization_ids()
returns text[] language sql stable security definer set search_path = public as $$
  with claims as (
    select
      nullif(btrim(auth.jwt() -> 'app_metadata' ->> 'primary_company'), '') as primary_company,
      nullif(btrim(auth.jwt() -> 'app_metadata' ->> 'company'), '') as company,
      case
        when jsonb_typeof(auth.jwt() -> 'app_metadata' -> 'allowed_companies') = 'array'
          then auth.jwt() -> 'app_metadata' -> 'allowed_companies'
        else '[]'::jsonb
      end as app_allowed
  ),
  src as (
    select primary_company as org_id from claims
    union all select company from claims
    union all
    select nullif(btrim(value), '') from claims,
      lateral jsonb_array_elements_text(app_allowed) as value
  )
  select coalesce(
    (
      select array_agg(distinct public.normalize_organization_id(org_id))
      from src
      where public.normalize_organization_id(org_id) is not null
    ),
    '{}'::text[]
  );
$$;

create or replace function public.user_can_access_commission_organization(p_organization_id text)
returns boolean language sql stable security definer set search_path = public as $$
  select
    public.normalize_organization_id(p_organization_id) is not null
    and public.normalize_organization_id(p_organization_id)
      = any (public.current_user_organization_ids());
$$;

create table if not exists public.chauffeurs (
  id bigint generated by default as identity primary key,
  auth_user_id uuid null,
  primary_company text null,
  nom text null
);

alter table public.chauffeurs add column if not exists primary_company text;

-- Catégories 6B (minimal pour FK 6D)
create table if not exists public.commission_categories (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null,
  code text not null,
  label text not null,
  description text null,
  display_order integer not null default 0,
  is_visible boolean not null default true,
  is_active boolean not null default true,
  is_system_default boolean not null default false,
  created_by uuid null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint commission_categories_organization_id_check check (
    organization_id ~ '^[a-z0-9_]+$'
  ),
  constraint commission_categories_org_code_unique unique (organization_id, code)
);
