-- Bootstrap minimal pour validation locale Bloc 6B (Supabase Postgres image).
-- Jetable — ne pas utiliser hors environnement de test local.

\set ON_ERROR_STOP on

-- auth.jwt() (souvent absent hors stack supabase start complète)
do $$
begin
  execute $fn$
    create or replace function auth.jwt()
    returns jsonb
    language sql
    stable
    as $body$
      select coalesce(
        nullif(current_setting('request.jwt.claims', true), '')::jsonb,
        '{}'::jsonb
      );
    $body$
  $fn$;
exception
  when insufficient_privilege then
    raise notice 'auth.jwt create skipped (privilege); continuing if already present';
end;
$$;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
end;
$$;

grant usage on schema public to authenticated, anon;
grant usage on schema auth to authenticated, anon;

create or replace function public.current_app_role()
returns text language sql stable as $$
  select nullif(auth.jwt() -> 'app_metadata' ->> 'role', '')
$$;

create or replace function public.is_admin_user()
returns boolean language sql stable as $$
  select public.current_app_role() = 'admin'
$$;

create or replace function public.is_direction_user()
returns boolean language sql stable as $$
  select public.current_app_role() = 'direction'
$$;

create or replace function public.current_app_permissions()
returns text[] language sql stable as $$
  select coalesce(
    (
      select array_agg(x)
      from jsonb_array_elements_text(
        coalesce(auth.jwt() -> 'app_metadata' -> 'permissions', '[]'::jsonb)
      ) as x
    ),
    '{}'::text[]
  )
$$;

-- Aligné sur le dépôt: Direction + permission; Admin géré via is_admin_user() dans les policies.
create or replace function public.has_app_permission(p_permission text)
returns boolean language sql stable as $$
  select
    public.is_direction_user()
    and p_permission = any (public.current_app_permissions())
$$;

create or replace function public.set_commissions_row_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.chauffeurs (
  id bigint generated by default as identity primary key,
  auth_user_id uuid null,
  primary_company text null,
  nom text null
);

create table if not exists public.sales_objectives (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'obj',
  period_start date not null default current_date,
  period_end date not null default current_date,
  target_type text not null default 'amount',
  target_amount numeric(14, 2) not null default 1,
  achieved_amount numeric(14, 2) not null default 0,
  achieved_sales_count integer not null default 0,
  status text not null default 'draft',
  company_context text null,
  chauffeur_id bigint null
);

-- Discovery seed: une org préexistante via chauffeur (pas de noms métier hardcodés)
insert into public.chauffeurs (primary_company, nom)
select 'seed_discovered_org', 'probe'
where not exists (
  select 1 from public.chauffeurs where primary_company = 'seed_discovered_org'
);
