-- Seed g├⌐n├⌐r├⌐ par scripts/build-communication-template-seed.mjs
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_created_direction_email', 'Horodateur', 'email', 'direction_admin', 'Exception horodateur ΓÇö direction (courriel)', 'Alerte lorsqu''une exception horodateur est en attente.', 'TAGORA Time ΓÇö Exception horodateur ├á traiter', $BODY$Employ├⌐ : {{employee_name}}
Type : {{exception_type}}
Motif : {{system_reason}}
Note employ├⌐ : {{employee_note}}
Approuver : {{approve_url}}
Refuser : {{reject_url}}
Voir : {{action_url}}$BODY$, 'TAGORA Time ΓÇö Exception horodateur ├á traiter', $BODY$Employ├⌐ : {{employee_name}}
Type : {{exception_type}}
Motif : {{system_reason}}
Note employ├⌐ : {{employee_note}}
Approuver : {{approve_url}}
Refuser : {{reject_url}}
Voir : {{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_created_direction_sms', 'Horodateur', 'sms', 'direction_admin', 'Exception horodateur ΓÇö direction (SMS)', 'SMS pour la direction.', null, $BODY$TAGORA Time. Exception {{exception_type}} ΓÇö {{employee_name}}. {{action_url}}$BODY$, null, $BODY$TAGORA Time. Exception {{exception_type}} ΓÇö {{employee_name}}. {{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_approved_employee_email', 'Horodateur', 'email', 'employee', 'Exception approuv├⌐e ΓÇö employ├⌐', null, 'Votre exception horodateur a ├⌐t├⌐ approuv├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande d'exception a ├⌐t├⌐ approuv├⌐e.

{{action_url}}$BODY$, 'Votre exception horodateur a ├⌐t├⌐ approuv├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande d'exception a ├⌐t├⌐ approuv├⌐e.

{{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_approved_employee_sms', 'Horodateur', 'sms', 'employee', 'Exception approuv├⌐e ΓÇö SMS', null, null, $BODY$TAGORA Time : exception horodateur approuv├⌐e. {{action_url}}$BODY$, null, $BODY$TAGORA Time : exception horodateur approuv├⌐e. {{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_rejected_employee_email', 'Horodateur', 'email', 'employee', 'Exception refus├⌐e ΓÇö employ├⌐', null, 'Votre exception horodateur a ├⌐t├⌐ refus├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ refus├⌐e.
Note : {{decision_note}}

{{action_url}}$BODY$, 'Votre exception horodateur a ├⌐t├⌐ refus├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ refus├⌐e.
Note : {{decision_note}}

{{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_rejected_employee_sms', 'Horodateur', 'sms', 'employee', 'Exception refus├⌐e ΓÇö SMS', null, null, $BODY$TAGORA Time : exception refus├⌐e. {{action_url}}$BODY$, null, $BODY$TAGORA Time : exception refus├⌐e. {{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_created_direction_email', 'Demandes d''horaire', 'email', 'direction_admin', 'Nouvelle demande d''horaire', null, 'Nouvelle demande d''horaire ou d''exception ├á approuver', $BODY$Demande de {{employee_name}}
Type : {{request_type}}
P├⌐riode : {{request_period}}
Justification : {{employee_note}}

{{action_url}}$BODY$, 'Nouvelle demande d''horaire ou d''exception ├á approuver', $BODY$Demande de {{employee_name}}
Type : {{request_type}}
P├⌐riode : {{request_period}}
Justification : {{employee_note}}

{{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_created_direction_sms', 'Demandes d''horaire', 'sms', 'direction_admin', 'Nouvelle demande ΓÇö SMS', null, null, $BODY$TAGORA Time : nouvelle demande horaire/exception de {{employee_name}}. {{action_url}}$BODY$, null, $BODY$TAGORA Time : nouvelle demande horaire/exception de {{employee_name}}. {{action_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_approved_employee_email', 'Demandes d''horaire', 'email', 'employee', 'Demande approuv├⌐e', null, 'Votre demande TAGORA Time a ├⌐t├⌐ approuv├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ approuv├⌐e.

{{dashboard_url}}$BODY$, 'Votre demande TAGORA Time a ├⌐t├⌐ approuv├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ approuv├⌐e.

{{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_approved_employee_sms', 'Demandes d''horaire', 'sms', 'employee', 'Demande approuv├⌐e ΓÇö SMS', null, null, $BODY$TAGORA Time : demande d'horaire approuv├⌐e. {{dashboard_url}}$BODY$, null, $BODY$TAGORA Time : demande d'horaire approuv├⌐e. {{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_rejected_employee_email', 'Demandes d''horaire', 'email', 'employee', 'Demande refus├⌐e', null, 'Votre demande TAGORA Time a ├⌐t├⌐ refus├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ refus├⌐e.

{{dashboard_url}}$BODY$, 'Votre demande TAGORA Time a ├⌐t├⌐ refus├⌐e', $BODY$Bonjour {{employee_name}},

Votre demande a ├⌐t├⌐ refus├⌐e.

{{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_rejected_employee_sms', 'Demandes d''horaire', 'sms', 'employee', 'Demande refus├⌐e ΓÇö SMS', null, null, $BODY$TAGORA Time : demande refus├⌐e. Consultez l'application.$BODY$, null, $BODY$TAGORA Time : demande refus├⌐e. Consultez l'application.$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_schedule_updated_email', 'Horaire employ├⌐', 'email', 'employee', 'Horaire mis ├á jour', null, 'Votre horaire TAGORA Time a ├⌐t├⌐ mis ├á jour', $BODY$Bonjour {{employee_name}},

Votre horaire a ├⌐t├⌐ mis ├á jour.

{{dashboard_url}}$BODY$, 'Votre horaire TAGORA Time a ├⌐t├⌐ mis ├á jour', $BODY$Bonjour {{employee_name}},

Votre horaire a ├⌐t├⌐ mis ├á jour.

{{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_schedule_updated_sms', 'Horaire employ├⌐', 'sms', 'employee', 'Horaire mis ├á jour ΓÇö SMS', null, null, $BODY$TAGORA Time : votre horaire a ├⌐t├⌐ mis ├á jour. {{dashboard_url}}$BODY$, null, $BODY$TAGORA Time : votre horaire a ├⌐t├⌐ mis ├á jour. {{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_shift_updated_email', 'Horaire employ├⌐', 'email', 'employee', 'Quart modifi├⌐', null, 'Votre horaire TAGORA Time a ├⌐t├⌐ mis ├á jour', $BODY$Bonjour {{employee_name}},

Un quart a ├⌐t├⌐ ajout├⌐ ou modifi├⌐.

{{dashboard_url}}$BODY$, 'Votre horaire TAGORA Time a ├⌐t├⌐ mis ├á jour', $BODY$Bonjour {{employee_name}},

Un quart a ├⌐t├⌐ ajout├⌐ ou modifi├⌐.

{{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_shift_updated_sms', 'Horaire employ├⌐', 'sms', 'employee', 'Quart modifi├⌐ ΓÇö SMS', null, null, $BODY$TAGORA Time : quart ajout├⌐ ou modifi├⌐. {{dashboard_url}}$BODY$, null, $BODY$TAGORA Time : quart ajout├⌐ ou modifi├⌐. {{dashboard_url}}$BODY$, true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_created_direction_email', 'D├⌐penses employ├⌐', 'email', 'direction_admin', 'D├⌐pense signal├⌐e (direction)', null, 'Nouvelle d├⌐pense employ├⌐', $BODY${{employee_name}} ΓÇö {{amount}} ΓÇö {{client_name}}
{{action_url}}$BODY$, 'Nouvelle d├⌐pense employ├⌐', $BODY${{employee_name}} ΓÇö {{amount}} ΓÇö {{client_name}}
{{action_url}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_created_direction_sms', 'D├⌐penses employ├⌐', 'sms', 'direction_admin', 'D├⌐pense signal├⌐e SMS', null, null, $BODY$TAGORA Time : d├⌐pense {{employee_name}} {{amount}}$BODY$, null, $BODY$TAGORA Time : d├⌐pense {{employee_name}} {{amount}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_processed_employee_email', 'D├⌐penses employ├⌐', 'email', 'employee', 'D├⌐pense trait├⌐e', null, 'Mise ├á jour d├⌐pense', $BODY$Bonjour {{employee_name}}, statut : {{expense_status}}$BODY$, 'Mise ├á jour d├⌐pense', $BODY$Bonjour {{employee_name}}, statut : {{expense_status}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_paid_employee_email', 'D├⌐penses employ├⌐', 'email', 'employee', 'D├⌐pense pay├⌐e', null, 'D├⌐pense pay├⌐e', $BODY$Bonjour {{employee_name}}, d├⌐pense pay├⌐e.$BODY$, 'D├⌐pense pay├⌐e', $BODY$Bonjour {{employee_name}}, d├⌐pense pay├⌐e.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_rejected_employee_email', 'D├⌐penses employ├⌐', 'email', 'employee', 'D├⌐pense refus├⌐e', null, 'D├⌐pense refus├⌐e', $BODY$Bonjour {{employee_name}}, d├⌐pense refus├⌐e.$BODY$, 'D├⌐pense refus├⌐e', $BODY$Bonjour {{employee_name}}, d├⌐pense refus├⌐e.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_status_updated_employee_sms', 'D├⌐penses employ├⌐', 'sms', 'employee', 'Statut d├⌐pense SMS', null, null, $BODY$TAGORA Time : d├⌐pense {{expense_status}}$BODY$, null, $BODY$TAGORA Time : d├⌐pense {{expense_status}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('incident_damage_created_direction_email', 'Incidents / dommages', 'email', 'direction_admin', 'Incident / dommage', null, 'Incident ├á v├⌐rifier', $BODY${{employee_name}} ΓÇö {{mission_name}}
{{employee_note}}
{{action_url}}$BODY$, 'Incident ├á v├⌐rifier', $BODY${{employee_name}} ΓÇö {{mission_name}}
{{employee_note}}
{{action_url}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('incident_damage_created_direction_sms', 'Incidents / dommages', 'sms', 'direction_admin', 'Incident SMS', null, null, $BODY$TAGORA Time : incident {{mission_name}}$BODY$, null, $BODY$TAGORA Time : incident {{mission_name}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_note_created_direction_email', 'Notes internes', 'email', 'direction_admin', 'Note interne', null, 'Nouvelle note interne', $BODY${{employee_name}} ΓÇö {{mission_name}}
{{employee_note}}$BODY$, 'Nouvelle note interne', $BODY${{employee_name}} ΓÇö {{mission_name}}
{{employee_note}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_note_created_direction_sms', 'Notes internes', 'sms', 'direction_admin', 'Note interne SMS', null, null, $BODY$TAGORA Time : note interne mission.$BODY$, null, $BODY$TAGORA Time : note interne mission.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_request_pending_direction_email', 'Comptes', 'email', 'direction_admin', 'Demande de compte', null, 'Nouvelle demande de compte', $BODY${{employee_name}} {{request_type}}
{{action_url}}$BODY$, 'Nouvelle demande de compte', $BODY${{employee_name}} {{request_type}}
{{action_url}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_request_pending_direction_sms', 'Comptes', 'sms', 'direction_admin', 'Demande compte SMS', null, null, $BODY$TAGORA Time : demande de compte.$BODY$, null, $BODY$TAGORA Time : demande de compte.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_approved_employee_email', 'Comptes', 'email', 'employee', 'Compte approuv├⌐', null, 'Votre acc├¿s TAGORA Time', $BODY$Bonjour {{employee_name}}, compte approuv├⌐. {{action_url}}$BODY$, 'Votre acc├¿s TAGORA Time', $BODY$Bonjour {{employee_name}}, compte approuv├⌐. {{action_url}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_rejected_employee_email', 'Comptes', 'email', 'employee', 'Compte refus├⌐', null, 'Demande refus├⌐e', $BODY$Bonjour {{employee_name}}, demande refus├⌐e.$BODY$, 'Demande refus├⌐e', $BODY$Bonjour {{employee_name}}, demande refus├⌐e.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('improvement_created_direction_email', 'Am├⌐liorations', 'email', 'direction_admin', 'Am├⌐lioration', null, 'Nouvelle suggestion', $BODY${{employee_note}}
{{action_url}}$BODY$, 'Nouvelle suggestion', $BODY${{employee_note}}
{{action_url}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('improvement_created_direction_sms', 'Am├⌐liorations', 'sms', 'direction_admin', 'Am├⌐lioration SMS', null, null, $BODY$TAGORA Time : nouvelle am├⌐lioration.$BODY$, null, $BODY$TAGORA Time : nouvelle am├⌐lioration.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_mention_email', 'Am├⌐liorations', 'email', 'direction_admin', 'Mention interne', null, 'Mention', $BODY${{employee_name}} vous a mentionn├⌐.
{{employee_note}}$BODY$, 'Mention', $BODY${{employee_name}} vous a mentionn├⌐.
{{employee_note}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_late_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Livraison en retard', null, 'Livraison en retard', $BODY$Livraison {{delivery_id}} {{client_name}}$BODY$, 'Livraison en retard', $BODY$Livraison {{delivery_id}} {{client_name}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_late_direction_sms', 'Livraisons / ramassages', 'sms', 'direction_admin', 'Livraison retard SMS', null, null, $BODY$TAGORA Time : livraison en retard {{delivery_id}}$BODY$, null, $BODY$TAGORA Time : livraison en retard {{delivery_id}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('pickup_late_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Ramassage en retard', null, 'Ramassage en retard', $BODY$Ramassage {{delivery_id}}$BODY$, 'Ramassage en retard', $BODY$Ramassage {{delivery_id}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('pickup_late_direction_sms', 'Livraisons / ramassages', 'sms', 'direction_admin', 'Ramassage SMS', null, null, $BODY$TAGORA Time : ramassage en retard$BODY$, null, $BODY$TAGORA Time : ramassage en retard$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_proof_missing_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Preuve manquante', null, 'Preuve manquante', $BODY$Livraison {{delivery_id}}$BODY$, 'Preuve manquante', $BODY$Livraison {{delivery_id}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('driver_missing_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Livreur manquant', null, 'Livreur manquant', $BODY$Mission {{mission_name}}$BODY$, 'Livreur manquant', $BODY$Mission {{mission_name}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_time_pending_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'Temps Titan', null, 'Temps ├á valider', $BODY${{employee_name}} {{request_period}}$BODY$, 'Temps ├á valider', $BODY${{employee_name}} {{request_period}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_km_pending_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'KM Titan', null, 'KM ├á valider', $BODY${{employee_name}}$BODY$, 'KM ├á valider', $BODY${{employee_name}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_billing_ready_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'Facturation pr├¬te', null, 'Refacturation pr├¬te', $BODY${{company_name}}$BODY$, 'Refacturation pr├¬te', $BODY${{company_name}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('notification_failure_direction_email', 'Syst├¿me', 'email', 'direction_admin', '├ëchec courriel', null, '├ëchec envoi', $BODY$Canal : d├⌐tail dans le centre d'alertes. {{employee_note}}$BODY$, '├ëchec envoi', $BODY$Canal : d├⌐tail dans le centre d'alertes. {{employee_note}}$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('notification_failure_direction_sms', 'Syst├¿me', 'sms', 'direction_admin', '├ëchec SMS', null, null, $BODY$TAGORA Time : ├⌐chec envoi notification$BODY$, null, $BODY$TAGORA Time : ├⌐chec envoi notification$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('missing_configuration_direction_email', 'Syst├¿me', 'email', 'direction_admin', 'Config manquante', null, 'Configuration manquante', $BODY$V├⌐rifier les cl├⌐s API et la configuration.$BODY$, 'Configuration manquante', $BODY$V├⌐rifier les cl├⌐s API et la configuration.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('missing_api_key_direction_email', 'Syst├¿me', 'email', 'direction_admin', 'Cl├⌐ API', null, 'Cl├⌐ API manquante', $BODY$Configurer Resend/Twilio.$BODY$, 'Cl├⌐ API manquante', $BODY$Configurer Resend/Twilio.$BODY$, true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
