-- Copie manuelle pour l’éditeur SQL Supabase si `supabase db push` est bloqué.
-- Source : supabase/migrations/20260509120000_app_communication_templates.sql
--
-- Inventaire et contenu des modèles courriel/SMS (éditable dans /direction/alertes/communications).

create table if not exists public.app_communication_templates (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  template_key text not null,
  category text not null,
  channel text not null,
  audience text not null,
  name text not null,
  description text null,
  subject text null,
  body text not null,
  active boolean not null default true,
  variables jsonb not null default '[]'::jsonb,
  default_subject text null,
  default_body text null,
  is_system boolean not null default true,
  implementation_status text not null default 'planned',
  updated_by uuid null references auth.users (id) on delete set null,
  constraint app_communication_templates_channel_chk check (channel in ('email','sms')),
  constraint app_communication_templates_audience_chk check (audience in ('employee','direction_admin','direction','admin')),
  constraint app_communication_templates_impl_chk check (implementation_status in ('connected','planned','inactive','to_configure')),
  constraint app_communication_templates_unique_triplet unique (template_key, channel, audience)
);

create index if not exists idx_app_communication_templates_cat
  on public.app_communication_templates (category);
create index if not exists idx_app_communication_templates_impl
  on public.app_communication_templates (implementation_status);

create or replace function public.set_communication_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_app_communication_templates_updated_at on public.app_communication_templates;
create trigger trg_app_communication_templates_updated_at
  before update on public.app_communication_templates
  for each row execute function public.set_communication_templates_updated_at();

alter table public.app_communication_templates enable row level security;

comment on table public.app_communication_templates is
  'Modèles de communications : textes éditables par direction/admin ; envoi via service role.';

-- Seed genere par scripts/build-communication-template-seed.mjs
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_created_direction_email', 'Horodateur', 'email', 'direction_admin', 'Exception horodateur — direction (courriel)', E'Alerte lorsqu''une exception horodateur est en attente.', E'TAGORA Time — Exception horodateur à traiter', E'Employé : {{employee_name}}\nType : {{exception_type}}\nMotif : {{system_reason}}\nNote employé : {{employee_note}}\nApprouver : {{approve_url}}\nRefuser : {{reject_url}}\nVoir : {{action_url}}', E'TAGORA Time — Exception horodateur à traiter', E'Employé : {{employee_name}}\nType : {{exception_type}}\nMotif : {{system_reason}}\nNote employé : {{employee_note}}\nApprouver : {{approve_url}}\nRefuser : {{reject_url}}\nVoir : {{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_created_direction_sms', 'Horodateur', 'sms', 'direction_admin', 'Exception horodateur — direction (SMS)', E'SMS pour la direction.', null, E'TAGORA Time. Exception {{exception_type}} — {{employee_name}}. {{action_url}}', null, E'TAGORA Time. Exception {{exception_type}} — {{employee_name}}. {{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_approved_employee_email', 'Horodateur', 'email', 'employee', 'Exception approuvée — employé', null, E'Votre exception horodateur a été approuvée', E'Bonjour {{employee_name}},\n\nVotre demande d''exception a été approuvée.\n\n{{action_url}}', E'Votre exception horodateur a été approuvée', E'Bonjour {{employee_name}},\n\nVotre demande d''exception a été approuvée.\n\n{{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_approved_employee_sms', 'Horodateur', 'sms', 'employee', 'Exception approuvée — SMS', null, null, E'TAGORA Time : exception horodateur approuvée. {{action_url}}', null, E'TAGORA Time : exception horodateur approuvée. {{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_rejected_employee_email', 'Horodateur', 'email', 'employee', 'Exception refusée — employé', null, E'Votre exception horodateur a été refusée', E'Bonjour {{employee_name}},\n\nVotre demande a été refusée.\nNote : {{decision_note}}\n\n{{action_url}}', E'Votre exception horodateur a été refusée', E'Bonjour {{employee_name}},\n\nVotre demande a été refusée.\nNote : {{decision_note}}\n\n{{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('horodateur_exception_rejected_employee_sms', 'Horodateur', 'sms', 'employee', 'Exception refusée — SMS', null, null, E'TAGORA Time : exception refusée. {{action_url}}', null, E'TAGORA Time : exception refusée. {{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_created_direction_email', 'Demandes d''horaire', 'email', 'direction_admin', 'Nouvelle demande d''horaire', null, E'Nouvelle demande d''horaire ou d''exception à approuver', E'Demande de {{employee_name}}\nType : {{request_type}}\nPériode : {{request_period}}\nJustification : {{employee_note}}\n\n{{action_url}}', E'Nouvelle demande d''horaire ou d''exception à approuver', E'Demande de {{employee_name}}\nType : {{request_type}}\nPériode : {{request_period}}\nJustification : {{employee_note}}\n\n{{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_created_direction_sms', 'Demandes d''horaire', 'sms', 'direction_admin', 'Nouvelle demande — SMS', null, null, E'TAGORA Time : nouvelle demande horaire/exception de {{employee_name}}. {{action_url}}', null, E'TAGORA Time : nouvelle demande horaire/exception de {{employee_name}}. {{action_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_approved_employee_email', 'Demandes d''horaire', 'email', 'employee', 'Demande approuvée', null, E'Votre demande TAGORA Time a été approuvée', E'Bonjour {{employee_name}},\n\nVotre demande a été approuvée.\n\n{{dashboard_url}}', E'Votre demande TAGORA Time a été approuvée', E'Bonjour {{employee_name}},\n\nVotre demande a été approuvée.\n\n{{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_approved_employee_sms', 'Demandes d''horaire', 'sms', 'employee', 'Demande approuvée — SMS', null, null, E'TAGORA Time : demande d''horaire approuvée. {{dashboard_url}}', null, E'TAGORA Time : demande d''horaire approuvée. {{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_rejected_employee_email', 'Demandes d''horaire', 'email', 'employee', 'Demande refusée', null, E'Votre demande TAGORA Time a été refusée', E'Bonjour {{employee_name}},\n\nVotre demande a été refusée.\n\n{{dashboard_url}}', E'Votre demande TAGORA Time a été refusée', E'Bonjour {{employee_name}},\n\nVotre demande a été refusée.\n\n{{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('schedule_request_rejected_employee_sms', 'Demandes d''horaire', 'sms', 'employee', 'Demande refusée — SMS', null, null, E'TAGORA Time : demande refusée. Consultez l''application.', null, E'TAGORA Time : demande refusée. Consultez l''application.', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_schedule_updated_email', 'Horaire employé', 'email', 'employee', 'Horaire mis à jour', null, E'Votre horaire TAGORA Time a été mis à jour', E'Bonjour {{employee_name}},\n\nVotre horaire a été mis à jour.\n\n{{dashboard_url}}', E'Votre horaire TAGORA Time a été mis à jour', E'Bonjour {{employee_name}},\n\nVotre horaire a été mis à jour.\n\n{{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_schedule_updated_sms', 'Horaire employé', 'sms', 'employee', 'Horaire mis à jour — SMS', null, null, E'TAGORA Time : votre horaire a été mis à jour. {{dashboard_url}}', null, E'TAGORA Time : votre horaire a été mis à jour. {{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_shift_updated_email', 'Horaire employé', 'email', 'employee', 'Quart modifié', null, E'Votre horaire TAGORA Time a été mis à jour', E'Bonjour {{employee_name}},\n\nUn quart a été ajouté ou modifié.\n\n{{dashboard_url}}', E'Votre horaire TAGORA Time a été mis à jour', E'Bonjour {{employee_name}},\n\nUn quart a été ajouté ou modifié.\n\n{{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_shift_updated_sms', 'Horaire employé', 'sms', 'employee', 'Quart modifié — SMS', null, null, E'TAGORA Time : quart ajouté ou modifié. {{dashboard_url}}', null, E'TAGORA Time : quart ajouté ou modifié. {{dashboard_url}}', true, '[]'::jsonb, 'connected', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_created_direction_email', 'Dépenses employé', 'email', 'direction_admin', 'Dépense signalée (direction)', null, E'Nouvelle dépense employé', E'{{employee_name}} — {{amount}} — {{client_name}}\n{{action_url}}', E'Nouvelle dépense employé', E'{{employee_name}} — {{amount}} — {{client_name}}\n{{action_url}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_created_direction_sms', 'Dépenses employé', 'sms', 'direction_admin', 'Dépense signalée SMS', null, null, E'TAGORA Time : dépense {{employee_name}} {{amount}}', null, E'TAGORA Time : dépense {{employee_name}} {{amount}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_processed_employee_email', 'Dépenses employé', 'email', 'employee', 'Dépense traitée', null, E'Mise à jour dépense', E'Bonjour {{employee_name}}, statut : {{expense_status}}', E'Mise à jour dépense', E'Bonjour {{employee_name}}, statut : {{expense_status}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_paid_employee_email', 'Dépenses employé', 'email', 'employee', 'Dépense payée', null, E'Dépense payée', E'Bonjour {{employee_name}}, dépense payée.', E'Dépense payée', E'Bonjour {{employee_name}}, dépense payée.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_rejected_employee_email', 'Dépenses employé', 'email', 'employee', 'Dépense refusée', null, E'Dépense refusée', E'Bonjour {{employee_name}}, dépense refusée.', E'Dépense refusée', E'Bonjour {{employee_name}}, dépense refusée.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('employee_expense_status_updated_employee_sms', 'Dépenses employé', 'sms', 'employee', 'Statut dépense SMS', null, null, E'TAGORA Time : dépense {{expense_status}}', null, E'TAGORA Time : dépense {{expense_status}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('incident_damage_created_direction_email', 'Incidents / dommages', 'email', 'direction_admin', 'Incident / dommage', null, E'Incident à vérifier', E'{{employee_name}} — {{mission_name}}\n{{employee_note}}\n{{action_url}}', E'Incident à vérifier', E'{{employee_name}} — {{mission_name}}\n{{employee_note}}\n{{action_url}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('incident_damage_created_direction_sms', 'Incidents / dommages', 'sms', 'direction_admin', 'Incident SMS', null, null, E'TAGORA Time : incident {{mission_name}}', null, E'TAGORA Time : incident {{mission_name}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_note_created_direction_email', 'Notes internes', 'email', 'direction_admin', 'Note interne', null, E'Nouvelle note interne', E'{{employee_name}} — {{mission_name}}\n{{employee_note}}', E'Nouvelle note interne', E'{{employee_name}} — {{mission_name}}\n{{employee_note}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_note_created_direction_sms', 'Notes internes', 'sms', 'direction_admin', 'Note interne SMS', null, null, E'TAGORA Time : note interne mission.', null, E'TAGORA Time : note interne mission.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_request_pending_direction_email', 'Comptes', 'email', 'direction_admin', 'Demande de compte', null, E'Nouvelle demande de compte', E'{{employee_name}} {{request_type}}\n{{action_url}}', E'Nouvelle demande de compte', E'{{employee_name}} {{request_type}}\n{{action_url}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_request_pending_direction_sms', 'Comptes', 'sms', 'direction_admin', 'Demande compte SMS', null, null, E'TAGORA Time : demande de compte.', null, E'TAGORA Time : demande de compte.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_approved_employee_email', 'Comptes', 'email', 'employee', 'Compte approuvé', null, E'Votre accès TAGORA Time', E'Bonjour {{employee_name}}, compte approuvé. {{action_url}}', E'Votre accès TAGORA Time', E'Bonjour {{employee_name}}, compte approuvé. {{action_url}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('account_rejected_employee_email', 'Comptes', 'email', 'employee', 'Compte refusé', null, E'Demande refusée', E'Bonjour {{employee_name}}, demande refusée.', E'Demande refusée', E'Bonjour {{employee_name}}, demande refusée.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('improvement_created_direction_email', 'Améliorations', 'email', 'direction_admin', 'Amélioration', null, E'Nouvelle suggestion', E'{{employee_note}}\n{{action_url}}', E'Nouvelle suggestion', E'{{employee_note}}\n{{action_url}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('improvement_created_direction_sms', 'Améliorations', 'sms', 'direction_admin', 'Amélioration SMS', null, null, E'TAGORA Time : nouvelle amélioration.', null, E'TAGORA Time : nouvelle amélioration.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('internal_mention_email', 'Améliorations', 'email', 'direction_admin', 'Mention interne', null, E'Mention', E'{{employee_name}} vous a mentionné.\n{{employee_note}}', E'Mention', E'{{employee_name}} vous a mentionné.\n{{employee_note}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_late_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Livraison en retard', null, E'Livraison en retard', E'Livraison {{delivery_id}} {{client_name}}', E'Livraison en retard', E'Livraison {{delivery_id}} {{client_name}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_late_direction_sms', 'Livraisons / ramassages', 'sms', 'direction_admin', 'Livraison retard SMS', null, null, E'TAGORA Time : livraison en retard {{delivery_id}}', null, E'TAGORA Time : livraison en retard {{delivery_id}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('pickup_late_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Ramassage en retard', null, E'Ramassage en retard', E'Ramassage {{delivery_id}}', E'Ramassage en retard', E'Ramassage {{delivery_id}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('pickup_late_direction_sms', 'Livraisons / ramassages', 'sms', 'direction_admin', 'Ramassage SMS', null, null, E'TAGORA Time : ramassage en retard', null, E'TAGORA Time : ramassage en retard', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('delivery_proof_missing_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Preuve manquante', null, E'Preuve manquante', E'Livraison {{delivery_id}}', E'Preuve manquante', E'Livraison {{delivery_id}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('driver_missing_direction_email', 'Livraisons / ramassages', 'email', 'direction_admin', 'Livreur manquant', null, E'Livreur manquant', E'Mission {{mission_name}}', E'Livreur manquant', E'Mission {{mission_name}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_time_pending_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'Temps Titan', null, E'Temps à valider', E'{{employee_name}} {{request_period}}', E'Temps à valider', E'{{employee_name}} {{request_period}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_km_pending_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'KM Titan', null, E'KM à valider', E'{{employee_name}}', E'KM à valider', E'{{employee_name}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('titan_billing_ready_direction_email', 'Refacturation Titan', 'email', 'direction_admin', 'Facturation prête', null, E'Refacturation prête', E'{{company_name}}', E'Refacturation prête', E'{{company_name}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('notification_failure_direction_email', 'Système', 'email', 'direction_admin', 'Échec courriel', null, E'Échec envoi', E'Canal : détail dans le centre d''alertes. {{employee_note}}', E'Échec envoi', E'Canal : détail dans le centre d''alertes. {{employee_note}}', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('notification_failure_direction_sms', 'Système', 'sms', 'direction_admin', 'Échec SMS', null, null, E'TAGORA Time : échec envoi notification', null, E'TAGORA Time : échec envoi notification', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('missing_configuration_direction_email', 'Système', 'email', 'direction_admin', 'Config manquante', null, E'Configuration manquante', E'Vérifier les clés API et la configuration.', E'Configuration manquante', E'Vérifier les clés API et la configuration.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
INSERT INTO public.app_communication_templates (template_key, category, channel, audience, name, description, subject, body, default_subject, default_body, active, variables, implementation_status, is_system) VALUES ('missing_api_key_direction_email', 'Système', 'email', 'direction_admin', 'Clé API', null, E'Clé API manquante', E'Configurer Resend/Twilio.', E'Clé API manquante', E'Configurer Resend/Twilio.', true, '[]'::jsonb, 'planned', true) ON CONFLICT (template_key, channel, audience) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, subject = EXCLUDED.subject, body = EXCLUDED.body, default_subject = EXCLUDED.default_subject, default_body = EXCLUDED.default_body, implementation_status = EXCLUDED.implementation_status, updated_at = timezone('utc', now());
