alter table if exists public.chauffeurs
  add column if not exists break_am_enabled boolean not null default false,
  add column if not exists break_am_time time,
  add column if not exists break_am_minutes integer,
  add column if not exists break_am_paid boolean not null default true,
  add column if not exists lunch_enabled boolean not null default false,
  add column if not exists lunch_time time,
  add column if not exists lunch_minutes integer,
  add column if not exists lunch_paid boolean not null default false,
  add column if not exists break_pm_enabled boolean not null default false,
  add column if not exists break_pm_time time,
  add column if not exists break_pm_minutes integer,
  add column if not exists break_pm_paid boolean not null default true,
  add column if not exists sms_alert_depart_terrain boolean not null default true,
  add column if not exists sms_alert_arrivee_terrain boolean not null default true,
  add column if not exists sms_alert_sortie boolean not null default true,
  add column if not exists sms_alert_retour boolean not null default true,
  add column if not exists sms_alert_pause_debut boolean not null default true,
  add column if not exists sms_alert_pause_fin boolean not null default true,
  add column if not exists sms_alert_dinner_debut boolean not null default true,
  add column if not exists sms_alert_dinner_fin boolean not null default true,
  add column if not exists sms_alert_quart_debut boolean not null default true,
  add column if not exists sms_alert_quart_fin boolean not null default true;

update public.chauffeurs
set
  break_am_enabled = coalesce(break_am_enabled, coalesce(break_1_minutes, 0) > 0),
  break_am_minutes = coalesce(break_am_minutes, break_1_minutes),
  break_am_paid = coalesce(break_am_paid, break_1_paid, true),
  lunch_enabled = coalesce(lunch_enabled, coalesce(break_2_minutes, 0) > 0),
  lunch_minutes = coalesce(lunch_minutes, break_2_minutes),
  lunch_paid = coalesce(lunch_paid, break_2_paid, false),
  break_pm_enabled = coalesce(break_pm_enabled, coalesce(break_3_minutes, 0) > 0),
  break_pm_minutes = coalesce(break_pm_minutes, break_3_minutes),
  break_pm_paid = coalesce(break_pm_paid, break_3_paid, true),
  sms_alert_depart_terrain = coalesce(sms_alerts_enabled, true),
  sms_alert_arrivee_terrain = coalesce(sms_alerts_enabled, true),
  sms_alert_sortie = coalesce(sms_alerts_enabled, true),
  sms_alert_retour = coalesce(sms_alerts_enabled, true),
  sms_alert_pause_debut = coalesce(sms_alerts_enabled, true),
  sms_alert_pause_fin = coalesce(sms_alerts_enabled, true),
  sms_alert_dinner_debut = coalesce(sms_alerts_enabled, true),
  sms_alert_dinner_fin = coalesce(sms_alerts_enabled, true),
  sms_alert_quart_debut = coalesce(sms_alerts_enabled, true),
  sms_alert_quart_fin = coalesce(sms_alerts_enabled, true)
where true;
