create table if not exists public.app_improvements (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  treated_at timestamptz null,
  deleted_at timestamptz null,
  created_by_user_id uuid null,
  created_by_email text null,
  created_by_role text null,
  module text not null,
  priority text not null,
  title text not null,
  description text not null,
  status text not null default 'en_attente',
  constraint app_improvements_module_check check (
    module in (
      'Horodateur',
      'Terrain',
      'Livraisons',
      'Documents',
      'Ressources',
      'Tableau de bord',
      'Approbation',
      'Authentification',
      'Generalites'
    )
  ),
  constraint app_improvements_priority_check check (
    priority in ('Faible', 'Moyenne', 'Elevee')
  ),
  constraint app_improvements_status_check check (
    status in ('en_attente', 'en_traitement', 'traitee', 'supprimee')
  )
);

create index if not exists idx_app_improvements_created_at
  on public.app_improvements (created_at desc);

create index if not exists idx_app_improvements_status
  on public.app_improvements (status);

alter table public.app_improvements enable row level security;

drop policy if exists app_improvements_select_authenticated on public.app_improvements;
create policy app_improvements_select_authenticated
  on public.app_improvements
  for select
  to authenticated
  using (true);

drop policy if exists app_improvements_insert_authenticated on public.app_improvements;
create policy app_improvements_insert_authenticated
  on public.app_improvements
  for insert
  to authenticated
  with check (true);

drop policy if exists app_improvements_update_direction on public.app_improvements;
create policy app_improvements_update_direction
  on public.app_improvements
  for update
  to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') in ('direction', 'admin', 'manager')
  )
  with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') in ('direction', 'admin', 'manager')
  );
