create table if not exists public.app_improvements (
  id bigint generated by default as identity primary key,
  module text not null,
  priority text not null,
  title text not null,
  description text not null,
  status text not null default 'nouveau',
  created_by_user_id uuid null references auth.users(id) on delete set null,
  created_by_email text null,
  created_by_role text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.app_improvements
  drop constraint if exists app_improvements_priority_check;

alter table if exists public.app_improvements
  add constraint app_improvements_priority_check
  check (priority in ('Faible', 'Moyenne', 'Elevee'));

alter table if exists public.app_improvements
  drop constraint if exists app_improvements_status_check;

alter table if exists public.app_improvements
  add constraint app_improvements_status_check
  check (status in ('nouveau', 'en_cours', 'traite', 'archive'));

create index if not exists idx_app_improvements_created_at
  on public.app_improvements (created_at desc);

create index if not exists idx_app_improvements_status
  on public.app_improvements (status, created_at desc);

alter table if exists public.app_improvements enable row level security;

drop policy if exists "app_improvements_select_authenticated" on public.app_improvements;
create policy "app_improvements_select_authenticated"
  on public.app_improvements
  for select
  to authenticated
  using (true);

drop policy if exists "app_improvements_insert_authenticated" on public.app_improvements;
create policy "app_improvements_insert_authenticated"
  on public.app_improvements
  for insert
  to authenticated
  with check (auth.uid() = created_by_user_id);
